package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.gradle
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Deploy'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Deploy")) {
    expectSteps {
        script {
            scriptContent = "ls -al"
        }
        script {
            scriptContent = "pwd"
        }
    }
    steps {
        insert(2) {
            script {
                scriptContent = "call gradlew.bat"
            }
        }
        insert(3) {
            maven {
                goals = "clean test"
                pomLocation = ".teamcity/pom.xml"
                runnerArgs = "-Dmaven.test.failure.ignore=true"
                mavenVersion = defaultProvidedVersion()
            }
        }
        insert(4) {
            gradle {
                tasks = "clean build"
                buildFile = ""
                gradleWrapperPath = ""
            }
        }
    }
}
