package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Parseyaml'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Parseyaml")) {
    expectSteps {
        script {
            name = "FooBar"
            scriptContent = "echo 'Hello World'"
        }
    }
    steps {
        insert(1) {
            maven {
                name = "testMvn"
                mavenVersion = defaultProvidedVersion()
            }
        }
    }
}
