package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "storage_settings"
                id = "PROJECT_EXT_5"
                param("secure:aws.secret.access.key", "credentialsJSON:cdb060ee-6584-479e-914f-a8dcc8f29bf1")
                param("aws.external.id", "TeamCity-server-89eb39bf-80e8-46c5-ba6d-9379769bd285")
                param("storage.name", "lambda")
                param("storage.s3.bucket.name", "origin-ig-dev-lambda-bucket")
                param("storage.type", "S3_storage")
                param("aws.access.key.id", "AKIAJHNIWIWGAFBYUQFA")
                param("aws.credentials.type", "aws.access.keys")
                param("aws.region.name", "ap-southeast-2")
                param("storage.s3.upload.presignedUrl.enabled", "true")
            }
        }
    }
}
